from .base import BaseViewsTestCase

from .registration import BaseRegistrationViewsTestCase
from .login import BaseLoginViewsTestCase
from .logout import BaseLogoutViewsTestCase
from .auth_info import BaseAuthInfoViewsTestCase
from .confirmation import BaseConfirmationViewsTestCase
from .password_reset import BasePasswordResetViewsTestCase
from .password_reset_confirmation import BasePasswordResetConfirmationViewsTestCase
